import { describe, expect, it } from "vitest";
import { createHash } from "node:crypto";
import * as fs from "node:fs";
import * as os from "node:os";
import * as path from "node:path";
import {
  checkStructuralHistorySchemaArtifacts,
  EXPECTED_WESLEY_CLI_VERSION,
  EXPECTED_WESLEY_L1_REGISTRY_HASH,
  readStructuralHistorySchemaManifest,
} from "../../../scripts/check-structural-history-schema-artifacts.js";
import {
  queryGitWarpImportBatchesOperation,
  queryStructuralReadingEvidenceOperation,
  queryStructuralReadingsOperation,
  type StructuralEvidenceKind,
  type StructuralReading,
  type StructuralReadingEvidence,
} from "../../../src/generated/graft-structural-history.js";

function sha256(text: string): string {
  return createHash("sha256").update(text).digest("hex");
}

function writeSchemaArtifactFixture(options: {
  readonly manifestOverrides?: Record<string, unknown>;
  readonly schemaText?: string;
  readonly generatedText?: string;
} = {}): string {
  const workspaceRoot = fs.mkdtempSync(path.join(os.tmpdir(), "graft-schema-artifacts-"));
  const schemaPath = "schemas/schema.graphql";
  const generatedTypesPath = "src/generated.ts";
  const schemaText = options.schemaText ?? "";
  const generatedText = options.generatedText ?? "/* @generated by Wesley. Do not edit. */\n";

  fs.mkdirSync(path.join(workspaceRoot, "schemas"), { recursive: true });
  fs.mkdirSync(path.join(workspaceRoot, "src"), { recursive: true });
  fs.writeFileSync(path.join(workspaceRoot, schemaPath), schemaText);
  fs.writeFileSync(path.join(workspaceRoot, generatedTypesPath), generatedText);
  fs.writeFileSync(
    path.join(workspaceRoot, "schemas/graft-structural-history.manifest.json"),
    `${JSON.stringify({
      schemaPath,
      generatedTypesPath,
      schemaSourceSha256: sha256(schemaText),
      generatedTypesSha256: sha256(generatedText),
      wesleyCliVersion: EXPECTED_WESLEY_CLI_VERSION,
      wesleyL1RegistryHash: EXPECTED_WESLEY_L1_REGISTRY_HASH,
      requiredTypes: [],
      requiredOperationConstants: [],
      requiredEvidenceLabels: [],
      ...options.manifestOverrides,
    }, null, 2)}\n`,
  );

  return workspaceRoot;
}

function writeFakeWesley(
  workspaceRoot: string,
  options: {
    readonly version?: string;
    readonly l1RegistryHash?: string;
    readonly generatedText?: string;
    readonly expectedSchemaPath?: string;
  } = {},
): string {
  const wesleyBin = path.join(workspaceRoot, "fake-wesley.cjs");
  const expectedSchemaPath = options.expectedSchemaPath ?? path.join(workspaceRoot, "schemas/schema.graphql");
  const script = [
    "#!/usr/bin/env node",
    'const fs = require("node:fs");',
    'const path = require("node:path");',
    'const invocationLogPath = path.join(__dirname, "fake-wesley-invocations.jsonl");',
    `const version = ${JSON.stringify(options.version ?? EXPECTED_WESLEY_CLI_VERSION)};`,
    `const l1RegistryHash = ${JSON.stringify(options.l1RegistryHash ?? EXPECTED_WESLEY_L1_REGISTRY_HASH)};`,
    `const generatedText = ${JSON.stringify(options.generatedText ?? "/* @generated by Wesley. Do not edit. */\n")};`,
    `const expectedSchemaPath = ${JSON.stringify(expectedSchemaPath)};`,
    "const args = process.argv.slice(2);",
    "fs.appendFileSync(invocationLogPath, `${JSON.stringify(args)}\\n`);",
    "function requireSchemaArgs(command) {",
    '  if (args[2] !== "--schema" || args[3] !== expectedSchemaPath) {',
    '    console.error(`${command} expected --schema ${expectedSchemaPath}, got ${args.join(" ")}`);',
    "    process.exit(64);",
    "  }",
    "}",
    'if (args[0] === "version") { console.log(version); process.exit(0); }',
    'if (args[0] === "schema" && args[1] === "hash") {',
    '  if (args.length !== 4) { console.error(`schema hash expected 4 args, got ${args.length}`); process.exit(64); }',
    '  requireSchemaArgs("schema hash");',
    "  console.log(l1RegistryHash);",
    "  process.exit(0);",
    "}",
    'if (args[0] === "emit" && args[1] === "typescript") {',
    '  if (args.length !== 6) { console.error(`emit typescript expected 6 args, got ${args.length}`); process.exit(64); }',
    '  requireSchemaArgs("emit typescript");',
    '  const outIndex = args.indexOf("--out");',
    '  if (outIndex === -1 || args[outIndex + 1] === undefined) {',
    '    console.error("missing --out");',
    "    process.exit(64);",
    "  }",
    "  const outPath = args[outIndex + 1];",
    "  fs.mkdirSync(path.dirname(outPath), { recursive: true });",
    "  fs.writeFileSync(outPath, generatedText);",
    "  process.exit(0);",
    "}",
    'console.error(`unexpected fake Wesley args: ${args.join(" ")}`);',
    "process.exit(64);",
    "",
  ].join("\n");

  fs.writeFileSync(wesleyBin, script, { mode: 0o755 });
  fs.chmodSync(wesleyBin, 0o755);
  return wesleyBin;
}

function readFakeWesleyInvocations(workspaceRoot: string): readonly (readonly string[])[] {
  const logPath = path.join(workspaceRoot, "fake-wesley-invocations.jsonl");
  if (!fs.existsSync(logPath)) {
    return [];
  }

  return fs
    .readFileSync(logPath, "utf8")
    .trim()
    .split("\n")
    .filter((line) => line.length > 0)
    .map((line) => JSON.parse(line) as readonly string[]);
}

function canonicalSchemaText(): string {
  return fs.readFileSync(path.join(process.cwd(), "schemas/graft-structural-history.graphql"), "utf8");
}

describe("Graft structural history schema authority", () => {
  it("keeps the GraphQL schema and Wesley-generated TypeScript artifact in lockstep", () => {
    expect(checkStructuralHistorySchemaArtifacts().violations).toEqual([]);
  });

  it("names the evidence states needed for Echo migration without changing Echo or Wesley", () => {
    const manifest = readStructuralHistorySchemaManifest();

    expect(manifest.requiredEvidenceLabels).toEqual([
      "ECHO_NATIVE",
      "GIT_WARP_IMPORTED",
      "FALLBACK_TRANSLATED",
    ]);
    expect(manifest.wesleyCliVersion).toBe(EXPECTED_WESLEY_CLI_VERSION);
  });

  it("exposes structural reading and import operations from the generated contract", () => {
    expect(queryStructuralReadingsOperation.directives.wes_footprint.reads).toEqual([
      "StructuralReading",
      "StructuralReadingEvidence",
    ]);
    expect(queryStructuralReadingEvidenceOperation.directives.wes_footprint.reads).toEqual([
      "StructuralReadingEvidence",
    ]);
    expect(queryGitWarpImportBatchesOperation.directives.wes_footprint.reads).toEqual([
      "GitWarpImportBatch",
    ]);
  });

  it("declares ordering invariants for structural source spans", () => {
    const schemaText = canonicalSchemaText();

    expect(schemaText).toContain('name: "source_span_offsets_are_ordered"');
    expect(schemaText).toContain("forall s in StructuralSourceSpan: s.endOffset >= s.startOffset");
    expect(schemaText).toContain('name: "source_span_lines_are_ordered_when_present"');
    expect(schemaText).toContain(
      "forall s in StructuralSourceSpan: s.startLine == null or s.endLine == null or s.endLine >= s.startLine",
    );
  });

  it("explains the invariant holder placeholder field", () => {
    expect(canonicalSchemaText()).toContain(
      "# Required because GraphQL object types must declare at least one field.\n  _placeholder: Boolean",
    );
  });

  it("keeps generated structural reading values behaviorally typed", () => {
    const evidenceKind: StructuralEvidenceKind = "FALLBACK_TRANSLATED";
    const evidence: StructuralReadingEvidence = {
      evidenceId: "evidence:1",
      evidenceKind,
      substrate: "GIT_WARP",
      basisId: "basis:head",
      sourceRef: "HEAD",
      migrationBatchId: null,
      nativeContinuumWitness: false,
      parity: "NOT_CHECKED",
      summary: "fallback git-warp compatibility evidence",
    };
    const reading: StructuralReading = {
      readingId: "reading:1",
      repositoryId: "repo:fixture",
      basisId: evidence.basisId,
      evidenceId: evidence.evidenceId,
      readingKind: "SYMBOL_REFERENCE_COUNT",
      freshness: "CURRENT",
      residualPosture: "COMPLETE",
      payloadDigest: "hash:payload",
      payloadJson: { referenceCount: 2 },
      summary: "symbol reference count",
    };

    expect(evidence.nativeContinuumWitness).toBe(false);
    expect(reading.evidenceId).toBe(evidence.evidenceId);
    expect(reading.readingKind).toBe("SYMBOL_REFERENCE_COUNT");
  });

  it("reports malformed manifest type names as drift violations without throwing", () => {
    const workspaceRoot = writeSchemaArtifactFixture({
      manifestOverrides: {
        requiredTypes: ["Structural(Symbol"],
      },
    });
    try {
      expect(checkStructuralHistorySchemaArtifacts(workspaceRoot).violations).toContain(
        "src/generated.ts is missing generated type Structural(Symbol.",
      );
    } finally {
      fs.rmSync(workspaceRoot, { recursive: true, force: true });
    }
  });

  it("rejects drift from the pinned Wesley L1 registry hash", () => {
    const workspaceRoot = writeSchemaArtifactFixture({
      manifestOverrides: {
        wesleyL1RegistryHash: "tampered-registry-hash",
      },
    });
    try {
      expect(checkStructuralHistorySchemaArtifacts(workspaceRoot).violations).toContain(
        `Unexpected Wesley L1 registry hash tampered-registry-hash; expected ${EXPECTED_WESLEY_L1_REGISTRY_HASH}.`,
      );
    } finally {
      fs.rmSync(workspaceRoot, { recursive: true, force: true });
    }
  });

  it("requires an explicit Wesley binary for hermetic generation checks", () => {
    const workspaceRoot = writeSchemaArtifactFixture();
    try {
      expect(checkStructuralHistorySchemaArtifacts(workspaceRoot, { requireWesley: true }).violations).toContain(
        "WESLEY_BIN is required for hermetic structural-history schema checks. Configure it to the pinned Wesley CLI binary.",
      );
    } finally {
      fs.rmSync(workspaceRoot, { recursive: true, force: true });
    }
  });

  it("regenerates and byte-compares generated TypeScript with configured Wesley", () => {
    const generatedText = "/* @generated by Wesley. Do not edit. */\nexport interface Fixture {}\n";
    const workspaceRoot = writeSchemaArtifactFixture({ generatedText });
    const wesleyBin = writeFakeWesley(workspaceRoot, { generatedText });

    try {
      const result = checkStructuralHistorySchemaArtifacts(workspaceRoot, {
        requireWesley: true,
        wesleyBin,
      });

      expect(result.violations).toEqual([]);
      expect(result.hermeticWesley).toEqual({
        bin: wesleyBin,
        version: EXPECTED_WESLEY_CLI_VERSION,
        l1RegistryHash: EXPECTED_WESLEY_L1_REGISTRY_HASH,
        regeneratedTypesSha256: sha256(generatedText),
      });
      expect(readFakeWesleyInvocations(workspaceRoot)).toEqual([
        ["version"],
        ["schema", "hash", "--schema", path.join(workspaceRoot, "schemas/schema.graphql")],
        [
          "emit",
          "typescript",
          "--schema",
          path.join(workspaceRoot, "schemas/schema.graphql"),
          "--out",
          expect.stringContaining("graft-structural-history.ts"),
        ],
      ]);
    } finally {
      fs.rmSync(workspaceRoot, { recursive: true, force: true });
    }
  });

  it("fails when Wesley emits different generated TypeScript", () => {
    const committedGeneratedText = "/* @generated by Wesley. Do not edit. */\nexport interface Committed {}\n";
    const regeneratedText = "/* @generated by Wesley. Do not edit. */\nexport interface Regenerated {}\n";
    const workspaceRoot = writeSchemaArtifactFixture({ generatedText: committedGeneratedText });
    const wesleyBin = writeFakeWesley(workspaceRoot, { generatedText: regeneratedText });

    try {
      expect(
        checkStructuralHistorySchemaArtifacts(workspaceRoot, {
          requireWesley: true,
          wesleyBin,
        }).violations,
      ).toEqual([
        expect.stringContaining("src/generated.ts does not match Wesley regenerated output for schemas/schema.graphql"),
      ]);
    } finally {
      fs.rmSync(workspaceRoot, { recursive: true, force: true });
    }
  });

  it("fails before emit when the configured Wesley binary reports the wrong L1 registry hash", () => {
    const workspaceRoot = writeSchemaArtifactFixture();
    const wesleyBin = writeFakeWesley(workspaceRoot, { l1RegistryHash: "tampered-live-hash" });

    try {
      const result = checkStructuralHistorySchemaArtifacts(workspaceRoot, {
        requireWesley: true,
        wesleyBin,
      });

      expect(result.violations).toEqual([
        `Wesley L1 registry hash tampered-live-hash does not match manifest ${EXPECTED_WESLEY_L1_REGISTRY_HASH}.`,
      ]);
      expect(result.hermeticWesley).toBeNull();
      expect(readFakeWesleyInvocations(workspaceRoot)).toEqual([
        ["version"],
        ["schema", "hash", "--schema", path.join(workspaceRoot, "schemas/schema.graphql")],
      ]);
    } finally {
      fs.rmSync(workspaceRoot, { recursive: true, force: true });
    }
  });

  it("fails when the configured Wesley binary reports the wrong version", () => {
    const workspaceRoot = writeSchemaArtifactFixture();
    const wesleyBin = writeFakeWesley(workspaceRoot, { version: "0.0.2" });

    try {
      expect(
        checkStructuralHistorySchemaArtifacts(workspaceRoot, {
          requireWesley: true,
          wesleyBin,
        }).violations,
      ).toContain(`Configured Wesley CLI version 0.0.2 does not match manifest ${EXPECTED_WESLEY_CLI_VERSION}.`);
      expect(readFakeWesleyInvocations(workspaceRoot)).toEqual([["version"]]);
    } finally {
      fs.rmSync(workspaceRoot, { recursive: true, force: true });
    }
  });
});
