import { describe, expect, it } from "vitest";
import { createHash } from "node:crypto";
import * as fs from "node:fs";
import * as os from "node:os";
import * as path from "node:path";
import {
  checkStructuralHistorySchemaArtifacts,
  EXPECTED_WESLEY_CLI_VERSION,
  EXPECTED_WESLEY_L1_REGISTRY_HASH,
  readStructuralHistorySchemaManifest,
} from "../../../scripts/check-structural-history-schema-artifacts.js";
import {
  queryGitWarpImportBatchesOperation,
  queryStructuralReadingEvidenceOperation,
  queryStructuralReadingsOperation,
  type StructuralEvidenceKind,
  type StructuralReading,
  type StructuralReadingEvidence,
} from "../../../src/generated/graft-structural-history.js";

function sha256(text: string): string {
  return createHash("sha256").update(text).digest("hex");
}

function writeSchemaArtifactFixture(options: {
  readonly manifestOverrides?: Record<string, unknown>;
  readonly schemaText?: string;
  readonly generatedText?: string;
} = {}): string {
  const workspaceRoot = fs.mkdtempSync(path.join(os.tmpdir(), "graft-schema-artifacts-"));
  const schemaPath = "schemas/schema.graphql";
  const generatedTypesPath = "src/generated.ts";
  const schemaText = options.schemaText ?? "";
  const generatedText = options.generatedText ?? "/* @generated by Wesley. Do not edit. */\n";

  fs.mkdirSync(path.join(workspaceRoot, "schemas"), { recursive: true });
  fs.mkdirSync(path.join(workspaceRoot, "src"), { recursive: true });
  fs.writeFileSync(path.join(workspaceRoot, schemaPath), schemaText);
  fs.writeFileSync(path.join(workspaceRoot, generatedTypesPath), generatedText);
  fs.writeFileSync(
    path.join(workspaceRoot, "schemas/graft-structural-history.manifest.json"),
    `${JSON.stringify({
      schemaPath,
      generatedTypesPath,
      schemaSourceSha256: sha256(schemaText),
      generatedTypesSha256: sha256(generatedText),
      wesleyCliVersion: EXPECTED_WESLEY_CLI_VERSION,
      wesleyL1RegistryHash: EXPECTED_WESLEY_L1_REGISTRY_HASH,
      requiredTypes: [],
      requiredOperationConstants: [],
      requiredEvidenceLabels: [],
      ...options.manifestOverrides,
    }, null, 2)}\n`,
  );

  return workspaceRoot;
}

function canonicalSchemaText(): string {
  return fs.readFileSync(path.join(process.cwd(), "schemas/graft-structural-history.graphql"), "utf8");
}

describe("Graft structural history schema authority", () => {
  it("keeps the GraphQL schema and Wesley-generated TypeScript artifact in lockstep", () => {
    expect(checkStructuralHistorySchemaArtifacts().violations).toEqual([]);
  });

  it("names the evidence states needed for Echo migration without changing Echo or Wesley", () => {
    const manifest = readStructuralHistorySchemaManifest();

    expect(manifest.requiredEvidenceLabels).toEqual([
      "ECHO_NATIVE",
      "GIT_WARP_IMPORTED",
      "FALLBACK_TRANSLATED",
    ]);
    expect(manifest.wesleyCliVersion).toBe(EXPECTED_WESLEY_CLI_VERSION);
  });

  it("exposes structural reading and import operations from the generated contract", () => {
    expect(queryStructuralReadingsOperation.directives.wes_footprint.reads).toEqual([
      "StructuralReading",
      "StructuralReadingEvidence",
    ]);
    expect(queryStructuralReadingEvidenceOperation.directives.wes_footprint.reads).toEqual([
      "StructuralReadingEvidence",
    ]);
    expect(queryGitWarpImportBatchesOperation.directives.wes_footprint.reads).toEqual([
      "GitWarpImportBatch",
    ]);
  });

  it("declares ordering invariants for structural source spans", () => {
    const schemaText = canonicalSchemaText();

    expect(schemaText).toContain('name: "source_span_offsets_are_ordered"');
    expect(schemaText).toContain("forall s in StructuralSourceSpan: s.endOffset >= s.startOffset");
    expect(schemaText).toContain('name: "source_span_lines_are_ordered_when_present"');
    expect(schemaText).toContain(
      "forall s in StructuralSourceSpan: s.startLine == null or s.endLine == null or s.endLine >= s.startLine",
    );
  });

  it("explains the invariant holder placeholder field", () => {
    expect(canonicalSchemaText()).toContain(
      "# Required because GraphQL object types must declare at least one field.\n  _placeholder: Boolean",
    );
  });

  it("keeps generated structural reading values behaviorally typed", () => {
    const evidenceKind: StructuralEvidenceKind = "FALLBACK_TRANSLATED";
    const evidence: StructuralReadingEvidence = {
      evidenceId: "evidence:1",
      evidenceKind,
      substrate: "GIT_WARP",
      basisId: "basis:head",
      sourceRef: "HEAD",
      migrationBatchId: null,
      nativeContinuumWitness: false,
      parity: "NOT_CHECKED",
      summary: "fallback git-warp compatibility evidence",
    };
    const reading: StructuralReading = {
      readingId: "reading:1",
      repositoryId: "repo:fixture",
      basisId: evidence.basisId,
      evidenceId: evidence.evidenceId,
      readingKind: "SYMBOL_REFERENCE_COUNT",
      freshness: "CURRENT",
      residualPosture: "COMPLETE",
      payloadDigest: "hash:payload",
      payloadJson: { referenceCount: 2 },
      summary: "symbol reference count",
    };

    expect(evidence.nativeContinuumWitness).toBe(false);
    expect(reading.evidenceId).toBe(evidence.evidenceId);
    expect(reading.readingKind).toBe("SYMBOL_REFERENCE_COUNT");
  });

  it("reports malformed manifest type names as drift violations without throwing", () => {
    const workspaceRoot = writeSchemaArtifactFixture({
      manifestOverrides: {
        requiredTypes: ["Structural(Symbol"],
      },
    });
    try {
      expect(checkStructuralHistorySchemaArtifacts(workspaceRoot).violations).toContain(
        "src/generated.ts is missing generated type Structural(Symbol.",
      );
    } finally {
      fs.rmSync(workspaceRoot, { recursive: true, force: true });
    }
  });

  it("rejects drift from the pinned Wesley L1 registry hash", () => {
    const workspaceRoot = writeSchemaArtifactFixture({
      manifestOverrides: {
        wesleyL1RegistryHash: "tampered-registry-hash",
      },
    });
    try {
      expect(checkStructuralHistorySchemaArtifacts(workspaceRoot).violations).toContain(
        `Unexpected Wesley L1 registry hash tampered-registry-hash; expected ${EXPECTED_WESLEY_L1_REGISTRY_HASH}.`,
      );
    } finally {
      fs.rmSync(workspaceRoot, { recursive: true, force: true });
    }
  });
});
