import { z } from "zod";
import {
  attributionSummarySchema,
  readEventSchema,
  stageEventSchema,
  transitionEventSchema,
} from "./causal-ontology.js";
import {
  mcpFragmentSchemas,
} from "./output-schema-fragments.js";
import type { McpToolName } from "./capabilities.js";

const {
  actualSchema,
  thresholdsSchema,
  budgetSchema,
  outlineEntrySchema,
  jumpEntrySchema,
  outlineDiffSchema,
  mapFileSchema,
  mapDirectorySchema,
  mapModeSchema,
  fileDiffSchema,
  burdenByKindSchema,
  sludgeReportSchema,
  burdenSummarySchema,
  runtimeObservabilitySchema,
  runtimeCausalContextSchema,
  runtimeStagedTargetSchema,
  persistedLocalHistorySummarySchema,
  repoConcurrencySummarySchema,
  precisionSymbolMatchSchema,
  codeRefsMatchSchema,
  codeRefsProvenanceSchema,
  structuralRefusalSchema,
  worldlineLayerSchema,
  activityViewSchema,
  causalStatusSchema,
  causalAttachSchema,
  workspaceAuthorizeSchema,
  workspaceRevokeSchema,
  workspaceStatusSchema,
  workspaceActionSchema,
  workspaceOverlaySummarySchema,
  workspaceOverlayFootingSchema,
  authorizedWorkspaceSchema,
  policyBoundarySchema,
  daemonStatusSchema,
  daemonSessionSchema,
  daemonRepoSchema,
  monitorStatusSchema,
  monitorActionSchema,
  repoTransitionSchema,
  repoSemanticTransitionSchema,
  sessionDepthSchema,
} = mcpFragmentSchemas;

export const mcpOutputBodySchemas = {
  safe_read: z.object({
    path: z.string(),
    projection: z.enum(["content", "outline", "refused", "error", "cache_hit", "diff"]),
    reason: z.string(),
    actual: actualSchema.optional(),
    thresholds: thresholdsSchema.optional(),
    sessionDepth: sessionDepthSchema.optional(),
    content: z.string().optional(),
    outline: z.array(outlineEntrySchema).optional(),
    jumpTable: z.array(jumpEntrySchema).optional(),
    estimatedBytesAvoided: z.number().int().nonnegative().optional(),
    next: z.array(z.string()).optional(),
    reasonDetail: z.string().optional(),
    readCount: z.number().int().nonnegative().optional(),
    lastReadAt: z.string().optional(),
    diff: outlineDiffSchema.optional(),
  }).strict(),
  file_outline: z.union([
    z.object({
      path: z.string(),
      outline: z.array(outlineEntrySchema),
      jumpTable: z.array(jumpEntrySchema),
      partial: z.boolean().optional(),
      reason: z.string().optional(),
      error: z.string().optional(),
      cacheHit: z.boolean().optional(),
    }).strict(),
    z.object({
      path: z.string(),
      projection: z.literal("refused"),
      reason: z.string(),
      reasonDetail: z.string().optional(),
      next: z.array(z.string()).optional(),
      actual: actualSchema.optional(),
    }).strict(),
  ]),
  read_range: z.object({
    path: z.string(),
    content: z.string().optional(),
    startLine: z.number().int().positive().optional(),
    endLine: z.number().int().positive().optional(),
    reason: z.string().optional(),
    truncated: z.boolean().optional(),
    clipped: z.boolean().optional(),
    projection: z.literal("refused").optional(),
    reasonDetail: z.string().optional(),
    next: z.array(z.string()).optional(),
    actual: actualSchema.optional(),
  }).strict(),
  changed_since: z.object({
    status: z.enum(["file_not_found", "refused", "unsupported", "unchanged", "no_previous_observation"]).optional(),
    reason: z.string().optional(),
    diff: outlineDiffSchema.optional(),
    consumed: z.boolean().optional(),
  }).strict(),
  graft_diff: z.object({
    base: z.string(),
    head: z.string(),
    files: z.array(fileDiffSchema),
    refused: z.array(structuralRefusalSchema).optional(),
    layer: worldlineLayerSchema,
  }).strict(),
  graft_since: z.object({
    base: z.string(),
    head: z.string(),
    files: z.array(fileDiffSchema),
    refused: z.array(structuralRefusalSchema).optional(),
    summary: z.string(),
    layer: z.literal("ref_view"),
  }).strict(),
  graft_map: z.object({
    directory: z.string(),
    files: z.array(mapFileSchema),
    directories: z.array(mapDirectorySchema).optional(),
    refused: z.array(structuralRefusalSchema).optional(),
    mode: mapModeSchema,
    summary: z.string(),
  }).strict(),
  code_show: z.object({
    symbol: z.string().optional(),
    kind: z.string().optional(),
    signature: z.string().optional(),
    path: z.string().optional(),
    identityId: z.string().optional(),
    exported: z.boolean().optional(),
    startLine: z.number().int().positive().optional(),
    endLine: z.number().int().positive().optional(),
    content: z.string().optional(),
    truncated: z.boolean().optional(),
    clipped: z.boolean().optional(),
    source: z.enum(["warp", "live"]),
    layer: worldlineLayerSchema,
    ambiguous: z.boolean().optional(),
    matches: z.array(precisionSymbolMatchSchema).optional(),
    error: z.string().optional(),
    projection: z.literal("refused").optional(),
    reason: z.string().optional(),
    reasonDetail: z.string().optional(),
    next: z.array(z.string()).optional(),
    actual: actualSchema.optional(),
  }).strict(),
  code_find: z.object({
    query: z.string(),
    kind: z.string().nullable(),
    matches: z.array(precisionSymbolMatchSchema).optional(),
    total: z.number().int().nonnegative().optional(),
    path: z.string().optional(),
    projection: z.literal("refused").optional(),
    reason: z.string().optional(),
    reasonDetail: z.string().optional(),
    next: z.array(z.string()).optional(),
    actual: actualSchema.optional(),
    source: z.enum(["warp", "live"]),
    layer: worldlineLayerSchema,
  }).strict(),
  code_refs: z.object({
    query: z.string(),
    mode: z.enum(["text", "import", "call", "property"]),
    scope: z.string(),
    matches: z.array(codeRefsMatchSchema).optional(),
    total: z.number().int().nonnegative().optional(),
    path: z.string().optional(),
    projection: z.literal("refused").optional(),
    reason: z.string().optional(),
    reasonDetail: z.string().optional(),
    next: z.array(z.string()).optional(),
    actual: actualSchema.optional(),
    source: z.literal("text_fallback"),
    provenance: codeRefsProvenanceSchema,
    layer: worldlineLayerSchema,
  }).strict(),
  daemon_repos: z.object({
    repos: z.array(daemonRepoSchema),
    filter: z.object({
      repoId: z.string().optional(),
      cwd: z.string().optional(),
    }).strict().optional(),
  }).strict(),
  daemon_status: daemonStatusSchema,
  daemon_sessions: z.object({
    sessions: z.array(daemonSessionSchema),
  }).strict(),
  daemon_monitors: z.object({
    monitors: z.array(monitorStatusSchema),
  }).strict(),
  monitor_start: monitorActionSchema,
  monitor_pause: monitorActionSchema,
  monitor_resume: monitorActionSchema,
  monitor_nudge: monitorActionSchema,
  monitor_stop: monitorActionSchema,
  workspace_authorize: workspaceAuthorizeSchema,
  workspace_authorizations: z.object({
    workspaces: z.array(authorizedWorkspaceSchema),
  }).strict(),
  workspace_revoke: workspaceRevokeSchema,
  workspace_bind: workspaceActionSchema.extend({ action: z.literal("bind") }).strict(),
  workspace_status: workspaceStatusSchema,
  activity_view: activityViewSchema,
  causal_status: causalStatusSchema,
  causal_attach: causalAttachSchema,
  workspace_rebind: workspaceActionSchema.extend({ action: z.literal("rebind") }).strict(),
  run_capture: z.object({
    output: z.string(),
    totalLines: z.number().int().nonnegative(),
    tailedLines: z.number().int().nonnegative(),
    logPath: z.string().nullable().optional(),
    logRedactions: z.number().int().nonnegative().optional(),
    logPersistenceEnabled: z.boolean().optional(),
    truncated: z.boolean(),
    disabled: z.boolean().optional(),
    error: z.string().optional(),
    stderr: z.string().optional(),
    policyBoundary: policyBoundarySchema,
  }).strict(),
  state_save: z.object({
    ok: z.boolean(),
    reason: z.string().optional(),
  }).strict(),
  state_load: z.object({
    content: z.string().nullable(),
  }).strict(),
  set_budget: z.object({
    budget: budgetSchema.nullable(),
  }).strict(),
  explain: z.object({
    code: z.string(),
    meaning: z.string().optional(),
    action: z.string().optional(),
    error: z.string().optional(),
    knownCodes: z.string().optional(),
  }).strict(),
  doctor: z.object({
    projectRoot: z.string(),
    parserHealthy: z.boolean(),
    thresholds: thresholdsSchema,
    sessionDepth: z.enum(["early", "mid", "late"]),
    totalMessages: z.number().int().nonnegative(),
    burdenSummary: burdenSummarySchema,
    runtimeObservability: runtimeObservabilitySchema,
    causalContext: runtimeCausalContextSchema,
    latestReadEvent: readEventSchema.nullable(),
    latestStageEvent: stageEventSchema.nullable(),
    latestTransitionEvent: transitionEventSchema.nullable(),
    repoConcurrency: repoConcurrencySummarySchema.nullable(),
    checkoutEpoch: z.number().int().nonnegative(),
    lastTransition: repoTransitionSchema.nullable(),
    semanticTransition: repoSemanticTransitionSchema.nullable(),
    workspaceOverlayId: z.string().nullable(),
    workspaceOverlay: workspaceOverlaySummarySchema.nullable(),
    workspaceOverlayFooting: workspaceOverlayFootingSchema,
    stagedTarget: runtimeStagedTargetSchema,
    attribution: attributionSummarySchema,
    persistedLocalHistory: persistedLocalHistorySummarySchema,
    recommendedNextAction: z.string(),
    sludge: sludgeReportSchema.optional(),
  }).strict(),
  stats: z.object({
    totalReads: z.number().int().nonnegative(),
    totalOutlines: z.number().int().nonnegative(),
    totalRefusals: z.number().int().nonnegative(),
    totalCacheHits: z.number().int().nonnegative(),
    totalBytesReturned: z.number().int().nonnegative(),
    totalBytesAvoidedByCache: z.number().int().nonnegative(),
    totalNonReadBytesReturned: z.number().int().nonnegative(),
    burdenByKind: burdenByKindSchema,
  }).strict(),
  graft_churn: z.object({
    entries: z.array(z.object({
      symbol: z.string(),
      filePath: z.string(),
      kind: z.string(),
      changeCount: z.number().int().positive(),
      lastChangedSha: z.string(),
      lastChangedDate: z.string(),
    }).strict()),
    totalSymbols: z.number().int().nonnegative(),
    totalCommitsAnalyzed: z.number().int().nonnegative(),
    summary: z.string(),
  }).strict(),
  graft_exports: z.object({
    base: z.string(),
    head: z.string(),
    added: z.array(z.object({
      symbol: z.string(),
      filePath: z.string(),
      kind: z.string(),
      changeType: z.literal("added"),
      signature: z.string().optional(),
    }).strict()),
    removed: z.array(z.object({
      symbol: z.string(),
      filePath: z.string(),
      kind: z.string(),
      changeType: z.literal("removed"),
      signature: z.string().optional(),
    }).strict()),
    changed: z.array(z.object({
      symbol: z.string(),
      filePath: z.string(),
      kind: z.string(),
      changeType: z.literal("signature_changed"),
      signature: z.string().optional(),
      previousSignature: z.string().optional(),
    }).strict()),
    semverImpact: z.enum(["major", "minor", "patch", "none"]),
    summary: z.string(),
  }).strict(),
  graft_log: z.object({
    entries: z.array(z.object({
      sha: z.string(),
      message: z.string(),
      author: z.string(),
      date: z.string(),
      symbols: z.object({
        added: z.array(z.object({
          name: z.string(),
          kind: z.string(),
          signature: z.string().optional(),
          exported: z.boolean(),
          filePath: z.string(),
        }).strict()),
        removed: z.array(z.object({
          name: z.string(),
          kind: z.string(),
          signature: z.string().optional(),
          exported: z.boolean(),
          filePath: z.string(),
        }).strict()),
        changed: z.array(z.object({
          name: z.string(),
          kind: z.string(),
          signature: z.string().optional(),
          exported: z.boolean(),
          filePath: z.string(),
        }).strict()),
      }).strict(),
      summary: z.string(),
    }).strict()),
    count: z.number().int().nonnegative(),
    layer: z.literal("commit_worldline"),
  }).strict(),
  graft_blame: z.object({
    symbol: z.string(),
    filePath: z.string().optional(),
    currentSignature: z.string().optional(),
    kind: z.string(),
    exported: z.boolean(),
    created: z.object({
      sha: z.string(),
      author: z.string(),
      date: z.string(),
      message: z.string(),
    }).strict().optional(),
    lastSignatureChange: z.object({
      sha: z.string(),
      author: z.string(),
      date: z.string(),
      message: z.string(),
      previousSignature: z.string().optional(),
    }).strict().optional(),
    changeCount: z.number().int().nonnegative(),
    referenceCount: z.number().int().nonnegative(),
    referencingFiles: z.array(z.string()),
    history: z.array(z.object({
      sha: z.string(),
      changeKind: z.string(),
      date: z.string(),
      author: z.string(),
      signature: z.string().optional(),
    }).strict()),
  }).strict(),
  graft_difficulty: z.object({
    symbol: z.string(),
    path: z.string().optional(),
    entries: z.array(z.object({
      symbol: z.string(),
      filePath: z.string(),
      kind: z.string(),
      score: z.number().nonnegative(),
      risk: z.enum(["low", "medium", "high"]),
      recommendation: z.enum(["refactor_freely", "refactor_with_tests", "plan_before_refactor"]),
      curvature: z.object({
        changeCount: z.number().int().nonnegative(),
        signatureChangeCount: z.number().int().nonnegative(),
        score: z.number().nonnegative(),
      }).strict(),
      friction: z.object({
        referenceCount: z.number().int().nonnegative(),
        referencingFiles: z.array(z.string()),
        score: z.number().nonnegative(),
      }).strict(),
    }).strict()),
    total: z.number().int().nonnegative(),
    summary: z.string(),
  }).strict(),
  graft_review: z.object({
    base: z.string(),
    head: z.string(),
    totalFiles: z.number().int().nonnegative(),
    categories: z.object({
      structural: z.number().int().nonnegative(),
      formatting: z.number().int().nonnegative(),
      test: z.number().int().nonnegative(),
      docs: z.number().int().nonnegative(),
      config: z.number().int().nonnegative(),
    }).strict(),
    files: z.array(z.object({
      path: z.string(),
      category: z.enum(["structural", "formatting", "test", "docs", "config"]),
      structuralChanges: z.object({
        added: z.number().int().nonnegative(),
        removed: z.number().int().nonnegative(),
        changed: z.number().int().nonnegative(),
      }).strict().optional(),
    }).strict()),
    breakingChanges: z.array(z.object({
      symbol: z.string(),
      kind: z.string(),
      filePath: z.string(),
      changeType: z.enum(["removed_export", "signature_changed", "type_changed"]),
      previousSignature: z.string().optional(),
      newSignature: z.string().optional(),
      impactedFiles: z.number().int().nonnegative(),
      impactedFilePaths: z.array(z.string()),
    }).strict()),
    summary: z.string(),
  }).strict(),
  knowledge_map: z.object({
    totalFiles: z.number().int().nonnegative(),
    totalSymbols: z.number().int().nonnegative(),
    files: z.array(z.object({
      path: z.string(),
      symbols: z.array(z.string()),
      readCount: z.number().int().positive(),
      lastReadAt: z.string(),
      stale: z.boolean(),
    }).strict()),
    staleFiles: z.array(z.string()),
    directoryCoverage: z.record(z.string(), z.number().int().nonnegative()),
  }).strict(),
} satisfies Record<McpToolName, z.ZodType>;
