#!/usr/bin/env tsx
import { createHash } from "node:crypto";
import { readFileSync } from "node:fs";
import * as path from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";

const SCRIPT_DIR = path.dirname(fileURLToPath(import.meta.url));
const DEFAULT_WORKSPACE_ROOT = path.resolve(SCRIPT_DIR, "..");
const DEFAULT_MANIFEST_PATH = "schemas/graft-structural-history.manifest.json";
const GENERATED_HEADER = "/* @generated by Wesley. Do not edit. */";

export interface StructuralHistorySchemaManifest {
  readonly schemaPath: string;
  readonly generatedTypesPath: string;
  readonly schemaSourceSha256: string;
  readonly generatedTypesSha256: string;
  readonly wesleyCliVersion: string;
  readonly wesleyL1RegistryHash: string;
  readonly requiredTypes: readonly string[];
  readonly requiredOperationConstants: readonly string[];
  readonly requiredEvidenceLabels: readonly string[];
}

export interface StructuralHistorySchemaArtifactCheck {
  readonly manifest: StructuralHistorySchemaManifest;
  readonly violations: readonly string[];
}

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === "object" && value !== null && !Array.isArray(value);
}

function readString(record: Record<string, unknown>, key: string): string {
  const value = record[key];
  if (typeof value !== "string" || value.trim().length === 0) {
    throw new Error(`Expected manifest field ${key} to be a non-empty string.`);
  }

  return value;
}

function readStringArray(record: Record<string, unknown>, key: string): readonly string[] {
  const value = record[key];
  if (!Array.isArray(value) || !value.every((item) => typeof item === "string")) {
    throw new Error(`Expected manifest field ${key} to be a string array.`);
  }

  return value;
}

export function readStructuralHistorySchemaManifest(
  workspaceRoot = DEFAULT_WORKSPACE_ROOT,
  manifestPath = DEFAULT_MANIFEST_PATH,
): StructuralHistorySchemaManifest {
  const manifestText = readFileSync(path.join(workspaceRoot, manifestPath), "utf8");
  const parsed = JSON.parse(manifestText) as unknown;
  if (!isRecord(parsed)) {
    throw new Error("Structural history schema manifest must be a JSON object.");
  }

  return {
    schemaPath: readString(parsed, "schemaPath"),
    generatedTypesPath: readString(parsed, "generatedTypesPath"),
    schemaSourceSha256: readString(parsed, "schemaSourceSha256"),
    generatedTypesSha256: readString(parsed, "generatedTypesSha256"),
    wesleyCliVersion: readString(parsed, "wesleyCliVersion"),
    wesleyL1RegistryHash: readString(parsed, "wesleyL1RegistryHash"),
    requiredTypes: readStringArray(parsed, "requiredTypes"),
    requiredOperationConstants: readStringArray(parsed, "requiredOperationConstants"),
    requiredEvidenceLabels: readStringArray(parsed, "requiredEvidenceLabels"),
  };
}

function sha256(text: string): string {
  return createHash("sha256").update(text).digest("hex");
}

function readWorkspaceFile(workspaceRoot: string, relativePath: string): string {
  return readFileSync(path.join(workspaceRoot, relativePath), "utf8");
}

function typePattern(typeName: string): RegExp {
  return new RegExp(`export (interface|type) ${typeName}\\b`, "u");
}

export function checkStructuralHistorySchemaArtifacts(
  workspaceRoot = DEFAULT_WORKSPACE_ROOT,
): StructuralHistorySchemaArtifactCheck {
  const manifest = readStructuralHistorySchemaManifest(workspaceRoot);
  const schemaText = readWorkspaceFile(workspaceRoot, manifest.schemaPath);
  const generatedText = readWorkspaceFile(workspaceRoot, manifest.generatedTypesPath);
  const violations: string[] = [];

  const schemaHash = sha256(schemaText);
  if (schemaHash !== manifest.schemaSourceSha256) {
    violations.push(
      `${manifest.schemaPath} sha256 ${schemaHash} does not match manifest ${manifest.schemaSourceSha256}.`,
    );
  }

  const generatedHash = sha256(generatedText);
  if (generatedHash !== manifest.generatedTypesSha256) {
    violations.push(
      `${manifest.generatedTypesPath} sha256 ${generatedHash} does not match manifest ${manifest.generatedTypesSha256}.`,
    );
  }

  if (!generatedText.startsWith(GENERATED_HEADER)) {
    violations.push(`${manifest.generatedTypesPath} is missing the Wesley generated-file header.`);
  }

  if (manifest.wesleyCliVersion !== "0.0.4") {
    violations.push(`Unexpected Wesley CLI version ${manifest.wesleyCliVersion}; expected 0.0.4.`);
  }

  for (const typeName of manifest.requiredTypes) {
    if (!typePattern(typeName).test(generatedText)) {
      violations.push(`${manifest.generatedTypesPath} is missing generated type ${typeName}.`);
    }
  }

  for (const operationName of manifest.requiredOperationConstants) {
    if (!generatedText.includes(`export const ${operationName} = {`)) {
      violations.push(`${manifest.generatedTypesPath} is missing operation constant ${operationName}.`);
    }
  }

  for (const evidenceLabel of manifest.requiredEvidenceLabels) {
    if (!schemaText.includes(evidenceLabel) || !generatedText.includes(evidenceLabel)) {
      violations.push(`Evidence label ${evidenceLabel} must exist in schema and generated types.`);
    }
  }

  return {
    manifest,
    violations,
  };
}

function isMainModule(): boolean {
  const invokedPath = process.argv[1];
  return invokedPath !== undefined && import.meta.url === pathToFileURL(invokedPath).href;
}

if (isMainModule()) {
  const result = checkStructuralHistorySchemaArtifacts();
  if (result.violations.length > 0) {
    for (const violation of result.violations) {
      console.error(violation);
    }
    process.exitCode = 1;
  } else {
    console.log(
      [
        "structural history schema artifacts verified",
        `schema=${result.manifest.schemaPath}`,
        `generated=${result.manifest.generatedTypesPath}`,
        `wesley=${result.manifest.wesleyCliVersion}`,
        `l1=${result.manifest.wesleyL1RegistryHash}`,
      ].join(" "),
    );
  }
}
