#!/usr/bin/env tsx
import { execFileSync } from "node:child_process";
import { createHash } from "node:crypto";
import { mkdtempSync, readFileSync, rmSync } from "node:fs";
import * as os from "node:os";
import * as path from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";

const SCRIPT_DIR = path.dirname(fileURLToPath(import.meta.url));
const DEFAULT_WORKSPACE_ROOT = path.resolve(SCRIPT_DIR, "..");
const DEFAULT_MANIFEST_PATH = "schemas/graft-structural-history.manifest.json";
const GENERATED_HEADER = "/* @generated by Wesley. Do not edit. */";
export const EXPECTED_WESLEY_CLI_VERSION = "0.0.4";
export const EXPECTED_WESLEY_L1_REGISTRY_HASH = "1f0956170eeec399e942fa8e418a4f23bc12ec40bf25f6e1de9510abbb15b832";

export interface StructuralHistorySchemaManifest {
  readonly schemaPath: string;
  readonly generatedTypesPath: string;
  readonly schemaSourceSha256: string;
  readonly generatedTypesSha256: string;
  readonly wesleyCliVersion: string;
  readonly wesleyL1RegistryHash: string;
  readonly requiredTypes: readonly string[];
  readonly requiredOperationConstants: readonly string[];
  readonly requiredEvidenceLabels: readonly string[];
}

export interface StructuralHistorySchemaArtifactCheck {
  readonly manifest: StructuralHistorySchemaManifest;
  readonly hermeticWesley: WesleyHermeticCheck | null;
  readonly violations: readonly string[];
}

export interface StructuralHistorySchemaArtifactCheckOptions {
  readonly requireWesley?: boolean;
  readonly wesleyBin?: string;
}

export interface WesleyHermeticCheck {
  readonly bin: string;
  readonly version: string;
  readonly l1RegistryHash: string;
  readonly regeneratedTypesSha256: string;
}

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === "object" && value !== null && !Array.isArray(value);
}

function readString(record: Record<string, unknown>, key: string): string {
  const value = record[key];
  if (typeof value !== "string" || value.trim().length === 0) {
    throw new Error(`Expected manifest field ${key} to be a non-empty string.`);
  }

  return value;
}

function readStringArray(record: Record<string, unknown>, key: string): readonly string[] {
  const value = record[key];
  if (!Array.isArray(value) || !value.every((item) => typeof item === "string")) {
    throw new Error(`Expected manifest field ${key} to be a string array.`);
  }

  return value;
}

export function readStructuralHistorySchemaManifest(
  workspaceRoot = DEFAULT_WORKSPACE_ROOT,
  manifestPath = DEFAULT_MANIFEST_PATH,
): StructuralHistorySchemaManifest {
  const manifestText = readFileSync(path.join(workspaceRoot, manifestPath), "utf8");
  const parsed = JSON.parse(manifestText) as unknown;
  if (!isRecord(parsed)) {
    throw new Error("Structural history schema manifest must be a JSON object.");
  }

  return {
    schemaPath: readString(parsed, "schemaPath"),
    generatedTypesPath: readString(parsed, "generatedTypesPath"),
    schemaSourceSha256: readString(parsed, "schemaSourceSha256"),
    generatedTypesSha256: readString(parsed, "generatedTypesSha256"),
    wesleyCliVersion: readString(parsed, "wesleyCliVersion"),
    wesleyL1RegistryHash: readString(parsed, "wesleyL1RegistryHash"),
    requiredTypes: readStringArray(parsed, "requiredTypes"),
    requiredOperationConstants: readStringArray(parsed, "requiredOperationConstants"),
    requiredEvidenceLabels: readStringArray(parsed, "requiredEvidenceLabels"),
  };
}

function sha256(text: string): string {
  return createHash("sha256").update(text).digest("hex");
}

function readWorkspaceFile(workspaceRoot: string, relativePath: string): string {
  return readFileSync(path.join(workspaceRoot, relativePath), "utf8");
}

function commandOutput(value: unknown): string | null {
  if (typeof value === "string") {
    return value;
  }
  if (Buffer.isBuffer(value)) {
    return value.toString("utf8");
  }
  return null;
}

function commandFailureMessage(error: unknown): string {
  if (!(error instanceof Error)) {
    return String(error);
  }

  const execError = error as Error & { readonly stderr?: unknown; readonly stdout?: unknown };
  const stderr = commandOutput(execError.stderr)?.trim();
  if (stderr !== undefined && stderr.length > 0) {
    return stderr;
  }

  const stdout = commandOutput(execError.stdout)?.trim();
  if (stdout !== undefined && stdout.length > 0) {
    return stdout;
  }

  return error.message;
}

function runWesleyText(
  wesleyBin: string,
  args: readonly string[],
  workspaceRoot: string,
): { readonly ok: true; readonly text: string } | { readonly ok: false; readonly error: string } {
  try {
    return {
      ok: true,
      text: execFileSync(wesleyBin, [...args], {
        cwd: workspaceRoot,
        encoding: "utf8",
        stdio: ["ignore", "pipe", "pipe"],
      }).trim(),
    };
  } catch (error) {
    return {
      ok: false,
      error: commandFailureMessage(error),
    };
  }
}

function escapeRegexLiteral(value: string): string {
  return value.replace(/[.*+?^${}()|[\]\\]/gu, "\\$&");
}

function typePattern(typeName: string): RegExp {
  return new RegExp(`export (interface|type) ${escapeRegexLiteral(typeName)}\\b`, "u");
}

function schemaRegistryTypes(schemaText: string): readonly string[] {
  const registryTypes: string[] = [];
  let currentType: string | null = null;
  for (const line of schemaText.split(/\r?\n/u)) {
    const typeMatch = /^type\s+([A-Za-z_][A-Za-z0-9_]*)\b/u.exec(line);
    if (typeMatch !== null) {
      currentType = typeMatch[1] ?? null;
      continue;
    }
    if (currentType !== null && line.includes("@wes_registry")) {
      registryTypes.push(currentType);
      currentType = null;
      continue;
    }
    if (currentType !== null && line.trim() === "{") {
      currentType = null;
    }
  }
  return registryTypes;
}

function checkHermeticWesleyGeneration(
  workspaceRoot: string,
  manifest: StructuralHistorySchemaManifest,
  committedGeneratedText: string,
  wesleyBin: string,
): { readonly hermeticWesley: WesleyHermeticCheck | null; readonly violations: readonly string[] } {
  const violations: string[] = [];
  const schemaPath = path.join(workspaceRoot, manifest.schemaPath);

  const version = runWesleyText(wesleyBin, ["version"], workspaceRoot);
  if (!version.ok) {
    return {
      hermeticWesley: null,
      violations: [`Failed to run configured Wesley binary ${wesleyBin}: ${version.error}`],
    };
  }
  if (version.text !== manifest.wesleyCliVersion) {
    violations.push(
      `Configured Wesley CLI version ${version.text} does not match manifest ${manifest.wesleyCliVersion}.`,
    );
  }

  const l1RegistryHash = runWesleyText(wesleyBin, ["schema", "hash", "--schema", schemaPath], workspaceRoot);
  if (!l1RegistryHash.ok) {
    return {
      hermeticWesley: null,
      violations: [
        ...violations,
        `Failed to compute Wesley L1 registry hash for ${manifest.schemaPath}: ${l1RegistryHash.error}`,
      ],
    };
  }
  if (l1RegistryHash.text !== manifest.wesleyL1RegistryHash) {
    violations.push(
      `Wesley L1 registry hash ${l1RegistryHash.text} does not match manifest ${manifest.wesleyL1RegistryHash}.`,
    );
  }

  const tempDir = mkdtempSync(path.join(os.tmpdir(), "graft-wesley-structural-history-"));
  try {
    const regeneratedPath = path.join(tempDir, "graft-structural-history.ts");
    const emit = runWesleyText(
      wesleyBin,
      ["emit", "typescript", "--schema", schemaPath, "--out", regeneratedPath],
      workspaceRoot,
    );
    if (!emit.ok) {
      return {
        hermeticWesley: null,
        violations: [
          ...violations,
          `Failed to regenerate ${manifest.generatedTypesPath} with Wesley: ${emit.error}`,
        ],
      };
    }

    const regeneratedText = readFileSync(regeneratedPath, "utf8");
    const regeneratedHash = sha256(regeneratedText);
    if (regeneratedText !== committedGeneratedText) {
      violations.push(
        `${manifest.generatedTypesPath} does not match Wesley regenerated output for ${manifest.schemaPath} ` +
          `(committed sha256 ${sha256(committedGeneratedText)}, regenerated sha256 ${regeneratedHash}).`,
      );
    }

    return {
      hermeticWesley: {
        bin: wesleyBin,
        version: version.text,
        l1RegistryHash: l1RegistryHash.text,
        regeneratedTypesSha256: regeneratedHash,
      },
      violations,
    };
  } finally {
    rmSync(tempDir, { recursive: true, force: true });
  }
}

export function checkStructuralHistorySchemaArtifacts(
  workspaceRoot = DEFAULT_WORKSPACE_ROOT,
  options: StructuralHistorySchemaArtifactCheckOptions = {},
): StructuralHistorySchemaArtifactCheck {
  const manifest = readStructuralHistorySchemaManifest(workspaceRoot);
  const schemaText = readWorkspaceFile(workspaceRoot, manifest.schemaPath);
  const generatedText = readWorkspaceFile(workspaceRoot, manifest.generatedTypesPath);
  const violations: string[] = [];
  let hermeticWesley: WesleyHermeticCheck | null = null;

  const schemaHash = sha256(schemaText);
  if (schemaHash !== manifest.schemaSourceSha256) {
    violations.push(
      `${manifest.schemaPath} sha256 ${schemaHash} does not match manifest ${manifest.schemaSourceSha256}.`,
    );
  }

  const generatedHash = sha256(generatedText);
  if (generatedHash !== manifest.generatedTypesSha256) {
    violations.push(
      `${manifest.generatedTypesPath} sha256 ${generatedHash} does not match manifest ${manifest.generatedTypesSha256}.`,
    );
  }

  if (!generatedText.startsWith(GENERATED_HEADER)) {
    violations.push(`${manifest.generatedTypesPath} is missing the Wesley generated-file header.`);
  }

  if (manifest.wesleyCliVersion !== EXPECTED_WESLEY_CLI_VERSION) {
    violations.push(
      `Unexpected Wesley CLI version ${manifest.wesleyCliVersion}; expected ${EXPECTED_WESLEY_CLI_VERSION}.`,
    );
  }

  if (manifest.wesleyL1RegistryHash !== EXPECTED_WESLEY_L1_REGISTRY_HASH) {
    violations.push(
      `Unexpected Wesley L1 registry hash ${manifest.wesleyL1RegistryHash}; expected ${EXPECTED_WESLEY_L1_REGISTRY_HASH}.`,
    );
  }

  for (const typeName of manifest.requiredTypes) {
    if (!typePattern(typeName).test(generatedText)) {
      violations.push(`${manifest.generatedTypesPath} is missing generated type ${typeName}.`);
    }
  }

  const requiredTypeNames = new Set(manifest.requiredTypes);
  for (const typeName of schemaRegistryTypes(schemaText)) {
    if (!requiredTypeNames.has(typeName)) {
      violations.push(`${manifest.schemaPath} registered type ${typeName} must be listed in manifest requiredTypes.`);
    }
  }

  for (const operationName of manifest.requiredOperationConstants) {
    if (!generatedText.includes(`export const ${operationName} = {`)) {
      violations.push(`${manifest.generatedTypesPath} is missing operation constant ${operationName}.`);
    }
  }

  for (const evidenceLabel of manifest.requiredEvidenceLabels) {
    if (!schemaText.includes(evidenceLabel) || !generatedText.includes(evidenceLabel)) {
      violations.push(`Evidence label ${evidenceLabel} must exist in schema and generated types.`);
    }
  }

  if (options.requireWesley === true) {
    if (options.wesleyBin === undefined || options.wesleyBin.trim().length === 0) {
      violations.push(
        "WESLEY_BIN is required for hermetic structural-history schema checks. " +
          "Configure it to the pinned Wesley CLI binary.",
      );
    } else {
      const hermeticResult = checkHermeticWesleyGeneration(workspaceRoot, manifest, generatedText, options.wesleyBin);
      hermeticWesley = hermeticResult.hermeticWesley;
      violations.push(...hermeticResult.violations);
    }
  }

  return {
    manifest,
    hermeticWesley,
    violations,
  };
}

function isMainModule(): boolean {
  const invokedPath = process.argv[1];
  return invokedPath !== undefined && import.meta.url === pathToFileURL(invokedPath).href;
}

if (isMainModule()) {
  const wesleyBin = process.env["WESLEY_BIN"];
  const result = checkStructuralHistorySchemaArtifacts(
    DEFAULT_WORKSPACE_ROOT,
    wesleyBin === undefined ? { requireWesley: true } : { requireWesley: true, wesleyBin },
  );
  if (result.violations.length > 0) {
    for (const violation of result.violations) {
      console.error(violation);
    }
    process.exitCode = 1;
  } else {
    console.log(
      [
        "structural history schema artifacts verified",
        `schema=${result.manifest.schemaPath}`,
        `generated=${result.manifest.generatedTypesPath}`,
        `wesley=${result.manifest.wesleyCliVersion}`,
        `l1=${result.manifest.wesleyL1RegistryHash}`,
        `regenerated=${result.hermeticWesley?.regeneratedTypesSha256 ?? "not-run"}`,
      ].join(" "),
    );
  }
}
